apptask/urls.py
from django.urls import path, include
from apptask.views import CreateTaskView, ChangePassword, Home

app_name='apptask'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('task-create/', CreateTaskView.as_view(), name='task-create'),
    path('password_change/', ChangePassword.as_view(), name='change-password'),
]

kotai_electronics/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('', include('apptask.urls')),

    # pass 'access_token' as Barrer auth token while making any request
    path('api/', include('apptask.api.urls')),
    path('api/', include('accounts.api.urls')),

    # path('api/token/create/', jwt_views.TokenObtainPairView.as_view(), name='token_create'),  # POST request (email, password is required)
    # path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'), 
]

templates/base.html
{% load static %}

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

	<meta name="author" content="">
	
	<title>
		Kotai Electronics
	</title>

	

	<!-- <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
	<!-- Bootstrap core CSS -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<!-- Material Design Bootstrap -->
	<link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

	<link href="{% static 'css/ubuntu.css' %}" rel='stylesheet' type='text/css'>
	
	{% block head %}
		
	{% endblock head %}
	<style>
		/* Custom page CSS
		-------------------------------------------------- */
		/* Not required for template or sticky footer method. */

		main > .container {
		padding: 60px 15px 0;
		}

		.footer {
		background-color: #f5f5f5;
		}

		.footer > .container {
		padding-right: 15px;
		padding-left: 15px;
		}

		code {
			font-size: 80%;
		}
		body{
			font-family: 'Ubuntu';
		}
		@media (min-width: 768px) {
			.text-center-mb {
				text-align: center;
			}
		}
	</style>
		
</head>

  <body class="d-flex flex-column h-100"  data-spy="scroll" data-target="#list-example" data-offset="250" style="position: relative; overflow: auto;">

	<header>
	  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
		<a class="navbar-brand" href="{% url 'apptask:home' %}">Kotai Electronics</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item">
			  <a class="nav-link {{home	}}" href="{% url 'apptask:home' %}">Home <span class="sr-only">(current)</span></a>
			</li>
            <li class="nav-item {{add_device}}">
                <a class="nav-link" href="{% url 'apptask:task-create' %}">Add Data</a>
            </li>
			
			{% if perms.apptask.change_device %}
			{% endif %}
			
		  </ul>


		  {% if user.is_authenticated %}
		  <ul class="navbar-nav my-2 my-md-0 ml-auto">	
			  <li class="nav-item dropdown">
				  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					  {{user.username}}
				  </a>
				  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
					  
					  
					  <a class="dropdown-item" href="/password_change/">Change Password</a>
					  <div class="dropdown-divider"></div>
					  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
				  </div>
			  </li>
		  </ul>
		{% endif %}
		</div>
	  </nav>
	</header>

	<!-- Begin page content -->
	<main role="main" class="mt-3">
		<div class="container w-100">
				
				{% block main_body %}					
					{% block body %}
						
					{% endblock body %}
				{% endblock main_body %}
					
			
		</div>
	</main>
	
	<!-- JQuery -->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<!-- Bootstrap tooltips -->
	<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
	<!-- Bootstrap core JavaScript -->
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- MDB core JavaScript -->
	<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

	<script src="{% static 'js/jspdf.min.js' %}"> </script>
	<script src="{% static 'js/jspdf.plugin.autotable.js' %}"> </script>
	<script src="{% static 'js/tableExport.min.js' %}"> </script>
	{% block bottom %}
		
	{% endblock bottom %}
	
</body>
</html>